// AUTO-GENERATED by scripts/generate-timezones.mjs — do not hand-edit.
// Regenerate with `npm run generate:timezones` and review the diff.
// Every distinct standard (non-DST) UTC offset (in minutes) across all IANA zones.

export const UTC_OFFSET_MINUTES = [
  -660, -600, -570, -540, -480, -420, -360, -300, -240, -210, -180, -120, -60, 0, 60, 120, 180, 210,
  240, 270, 300, 330, 345, 360, 390, 420, 480, 525, 540, 570, 600, 630, 660, 720, 765, 780, 840,
] as const;
